projektzaginione/Models/LosePeople.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace projektzaginione.Models
{
    public class LosePeople
    {
        public int Id { get; set; }

        public string Imie { get; set; }

        public string Nazwisko { get; set; }

        public int Wiek { get; set; }

        public string Opis { get; set; }
        [DisplayName("Data zaginiecia")]
        public string Data_zaginiecia { get; set; }
        [DisplayName("Znaki szczegolne")]
        public string Znaki_szczegolne { get; set; }

        public string Lokalizacja { get; set; }

    }
}

projektzaginione/Controllers/LosePeopleController.cs
using projektzaginione.DAL;
using projektzaginione.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace projektzaginione.Controllers
{
    public class LosePeopleController : Controller
    {
        private dataContext db = new dataContext();
        // GET: LosePeople
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            return View(db.LosePeople.ToList());
        }
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Imie, Nazwisko, Wiek, Opis, Data_zaginiecia, Znaki_szczegolne, Lokalizacja")]LosePeople losepeople)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.LosePeople.Add(losepeople);
                    db.SaveChanges();
                    return RedirectToAction("List");
                }
            }
            catch (RetryLimitExceededException /* dex */)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return View(losepeople);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LosePeople losepeople = db.LosePeople.Find(id);
            if (losepeople == null)
            {
                return HttpNotFound();
            }
            return View(losepeople);
        }

    }
}

projektzaginione/Views/LosePeople/Create.cshtml
@model projektzaginione.Models.LosePeople
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Nowy Poszukiwany</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Imie, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Imie, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Imie, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Nazwisko, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nazwisko, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nazwisko, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Wiek, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Wiek, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Wiek, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Opis, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Opis, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Opis, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Data_zaginiecia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Data_zaginiecia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Data_zaginiecia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Znaki_szczegolne, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Znaki_szczegolne, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Znaki_szczegolne, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Lokalizacja, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Lokalizacja, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Lokalizacja, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

projektzaginione/Views/LosePeople/Details.cshtml
@model projektzaginione.Models.LosePeople
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Wiecej Informacji</h2>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Imie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nazwisko)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nazwisko)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Wiek)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Wiek)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Data_zaginiecia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data_zaginiecia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Znaki_szczegolne)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Znaki_szczegolne)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lokalizacja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lokalizacja)
        </dd>
    </dl>
</div>

<p>
    @Html.ActionLink("Wroc", "List")
</p>

projektzaginione/Views/LosePeople/List.cshtml
@model IEnumerable<projektzaginione.Models.LosePeople>
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista Zaginionych</h2>
<p>
    @Html.ActionLink("Dodaj zaginionego", "Create", "LosePeople", null, new { @class = "btn btn-primary" })
</p>
<table id="peoples" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Imie</th>
            <th>Nazwisko</th>
            <th>Wiek</th>
            <th>Lokalizacja</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Imie)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nazwisko)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Wiek)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Lokalizacja)
                </td>
                <td>
                    @Html.ActionLink("Wiecej Informacji", "Details", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>